---
- name: Become block
  become: true
  block:
    - name: Set Ansible Python interpreter to k8s virtualenv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/libexec/platform-python
  
    - name: Install tcsh and Red Hat Lightspeed assistant
      ansible.builtin.command: >-
        dnf install -y tcsh
      register: install_tcsh
      failed_when: install_tcsh.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Enable copr repository
      ansible.builtin.command: >-
        dnf copr enable -y @rhel-lightspeed/command-line-assistant
      register: enable_copr
      failed_when: enable_copr.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Install command-line-assistant
      ansible.builtin.command: >-
        dnf install -y command-line-assistant
      register: install_cla
      failed_when: install_cla.rc != 0
      delegate_to: "{{ _hostname_ }}"
      
    - name: Install httpd
      ansible.builtin.command: >-
        dnf install -y httpd
      register: install_httpd
      failed_when: install_httpd.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Install firewalld
      ansible.builtin.command: >-
        dnf install -y firewalld
      register: install_firewalld
      failed_when: install_firewalld.rc != 0
      delegate_to: "{{ _hostname_ }}"

    - name: Enable and start firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: yes
        state: started
      register: start_firewalld
      delegate_to: "{{ _hostname_ }}"

    - name: Allow HTTP traffic through firewalld
      ansible.builtin.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      register: allow_http
      delegate_to: "{{ _hostname_ }}"

    - name: Allow HTTPS traffic through firewalld
      ansible.builtin.firewalld:
        service: https
        permanent: yes
        state: enabled
        immediate: yes
      register: allow_https
      delegate_to: "{{ _hostname_ }}"

    - name: Reload firewalld to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      register: reload_firewalld
      delegate_to: "{{ _hostname_ }}"

    - name: Install git using direct dnf command
      ansible.builtin.command: >-
        dnf install -y git
      register: install_git
      retries: 3
      delay: 5
      until: install_git.rc == 0
      delegate_to: "{{ _hostname_ }}"

    - name: Clean up any existing temporary directory
      ansible.builtin.file:
        path: /tmp/users_gist
        state: absent
      delegate_to: "{{ _hostname_ }}"

    - name: Clone gist and move users.csv to home directory
      ansible.builtin.shell: |
        git clone https://gist.github.com/1c8afb3087be6e4ec8f1df0a5e50124d.git /tmp/users_gist &&
        mv /tmp/users_gist/users.csv ~/users.csv
      args:
        executable: /bin/bash
      register: clone_gist
      retries: 3
      delay: 5
      until: clone_gist is succeeded
      delegate_to: "{{ _hostname_ }}"

    - name: Verify users.csv exists
      ansible.builtin.stat:
        path: ~/users.csv
      register: users_file
      delegate_to: "{{ _hostname_ }}"

    - name: Show result
      ansible.builtin.debug:
        msg: "users.csv successfully copied to home directory"
      when: users_file.stat.exists
      delegate_to: "{{ _hostname_ }}"

    - name: Set Ansible Python interpreter to k8s virtualenv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python
